
# Build wedge inflation factor table ---------------------------------------------------------------
  binfcreator = function(X, base){
    values = base$var/X$var
    return(values)
  }
  base = c(2,12,22,32)
  
  binf_dt = data.table()
  
  for(i in 0:3){
    binf_dt_temp = lapply(tlist[c(1,3:10) + i*10], FUN = binfcreator, base = tlist[[base[i +1]]]) %>% bind_rows() %>% gather() %>% 
      separate(col = key, sep = '\\.', into = c('model', '.id')) %>% as.data.table()
    binf_dt = rbindlist(list(binf_dt,binf_dt_temp))
  }
  
  
  binf_sum = binf_dt[, .(
    mean = mean(value),
    sd = sd(value)
  ), by = .(model, .id)]
  
  binfmat = matrix(
    data = c(rbind(
      comma(binf_sum[,mean], accuracy = .0001),
      comma(binf_sum[,sd], accuracy = .0001) %>% paste0("(", ., ")")
    )),
    ncol = 4,
    byrow = F
  )
  
  nm = binf_dt[,model] %>% uniqueN()
  
  binfmat %<>% cbind(c(rbind(binf_sum[1:nm,model], rep("", nm))), .)
  
  binfmat = cbind(binfmat[,1], "&", binfmat[,2], "&", binfmat[,3], "&", binfmat[,4], "&", binfmat[,5])
  binfmat %<>% cbind(
    .,
    c(rbind(rep("\\\\[-0.1em]", nm), rep("\\\\[0.3em]", nm)))
  )
  # Convert to character vector for TeX
  sum_tex = binfmat %>% knitr::kable(format = "pandoc") %>%
    as.character() %>% tail(-1) %>% head(-1)
  # Add top part
  sum_tex %<>% c(
    "% NOTE: Do not edit. This file will be overwritten.",
    "% This file is generated by 'codeR/table-results.R'",
    "",
    "\\begin{table}[!htbp] \\centering",
    "  \\caption{\\textbf{Simulation results}: Variance Bias Inflation Factor by Method}",
    "  \\label{tab:Variance-on-bias}",
    paste(c("\\begin{tabular}{@{\\extracolsep{3pt}}l", rep("c", 4), "@{}}"), collapse = ""),
    "  \\toprule",
    "  \\ra{1.5}",
    paste0(
      "  \\textbf{DGP:} & ",
      "\\multicolumn{3}{c}{100 \\textit{mixed} instruments} & ",
      "7 strong instruments \\\\ ",
      "\\cmidrule(lr){2-4} \\cmidrule(lr){5-5}"
    ),
    "  & (1) & (2) & (3) & (4) \\\\",
    "  \\midrule",
    "",
    .
  )
  # Add bottom part
  sum_tex %<>% c(
    "",
    "\\bottomrule",
    "\\\\[-0.9em]",
    "\\end{tabular}",
    paste0("\\caption*{\\raggedright\\small ",  tmp_caption," }"),
    "\\end{table}"
  ) 
  # Capture to write
  sum_tex = capture.output(expr = cat(paste0(sum_tex, "\n")))
  
  write(
    sum_tex,
    here("Tables", "bias-inflation-factor.tex")
  )